"""本地 backtrader 类型 stub — 仅覆盖 floatshare 实际用到的 API。

backtrader 用元类动态生成 params 和 Lines，pyright/mypy 无法跟踪。
我们只声明接口，让类型检查器能识别构造参数和方法签名。
"""

from typing import Any, ClassVar

# --- TimeFrame -----------------------------------------------------------------
class TimeFrame:
    Days: ClassVar[int]
    Weeks: ClassVar[int]
    Months: ClassVar[int]
    Years: ClassVar[int]
    Minutes: ClassVar[int]
    Ticks: ClassVar[int]

# --- Strategy ------------------------------------------------------------------
class _Position:
    size: float
    price: float

class _Line:
    def __getitem__(self, idx: int) -> float: ...
    def __len__(self) -> int: ...

class _Data:
    _name: str
    open: _Line
    high: _Line
    low: _Line
    close: _Line
    volume: _Line
    def __len__(self) -> int: ...

class _Broker:
    def getcash(self) -> float: ...
    def getvalue(self) -> float: ...
    def setcash(self, cash: float) -> None: ...
    def addcommissioninfo(self, comm: Any) -> None: ...
    def set_slippage_perc(self, perc: float) -> None: ...
    def setcommission(self, **kwargs: Any) -> None: ...

class _Params:
    def __getattr__(self, name: str) -> Any: ...

class Strategy:
    datas: list[_Data]
    broker: _Broker
    p: _Params
    params: tuple[tuple[str, Any], ...]

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def buy(self, data: _Data | None = ..., size: float | None = ..., **kwargs: Any) -> Any: ...
    def sell(self, data: _Data | None = ..., size: float | None = ..., **kwargs: Any) -> Any: ...
    def close(self, data: _Data | None = ..., **kwargs: Any) -> Any: ...
    def getposition(self, data: _Data | None = ...) -> _Position: ...
    def next(self) -> None: ...
    def log(self, msg: str) -> None: ...

# --- Commission ----------------------------------------------------------------
class CommInfoBase:
    COMM_PERC: ClassVar[int]
    COMM_FIXED: ClassVar[int]
    p: _Params
    params: tuple[tuple[str, Any], ...]
    def __init__(self, **kwargs: Any) -> None: ...
    def _getcommission(self, size: float, price: float, pseudoexec: bool) -> float: ...

# --- Cerebro -------------------------------------------------------------------
class Cerebro:
    broker: _Broker
    def __init__(self, **kwargs: Any) -> None: ...
    def adddata(self, data: Any, name: str | None = ...) -> None: ...
    def addstrategy(self, strategy: type[Strategy], **kwargs: Any) -> None: ...
    def addanalyzer(self, analyzer: type, _name: str = ..., **kwargs: Any) -> None: ...
    def run(self, **kwargs: Any) -> list[Strategy]: ...

# --- Sub-modules ---------------------------------------------------------------
class _Indicator:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, idx: int) -> float: ...
    def __len__(self) -> int: ...

class indicators:  # noqa: N801
    class SMA(_Indicator): ...
    class EMA(_Indicator): ...
    class CrossOver(_Indicator): ...
    class Highest(_Indicator): ...
    class Lowest(_Indicator): ...
    class ATR(_Indicator): ...
    class RSI(_Indicator): ...

class feeds:  # noqa: N801
    class PandasData:
        def __init__(self, **kwargs: Any) -> None: ...

class _Analyzer:
    def get_analysis(self) -> dict[Any, Any]: ...

class analyzers:  # noqa: N801
    class TimeReturn(_Analyzer): ...
    class SharpeRatio(_Analyzer): ...
    class DrawDown(_Analyzer): ...
    class TradeAnalyzer(_Analyzer): ...

__all__ = [
    "Cerebro",
    "CommInfoBase",
    "Strategy",
    "TimeFrame",
    "analyzers",
    "feeds",
    "indicators",
]

def __getattr__(name: str) -> Any: ...  # 兜底：未声明的访问返回 Any
